const { usedInfo } = require('./usedInfo')

const rawInput = `https://www.crunchbase.com/organization/strayos,
https://www.crunchbase.com/organization/typelead,
https://www.crunchbase.com/organization/rapid-rms,
https://www.crunchbase.com/organization/immersedteam,
https://www.crunchbase.com/organization/4degrees,
https://www.crunchbase.com/organization/roadbotics-inc,
https://www.crunchbase.com/organization/immersedteam,
https://www.crunchbase.com/organization/harbor-pension,
https://www.crunchbase.com/organization/swag-com,
https://www.crunchbase.com/organization/allie-2,
https://www.crunchbase.com/organization/abode-3,
https://www.crunchbase.com/organization/elemetric,
https://www.crunchbase.com/organization/omelas,
https://www.crunchbase.com/organization/paladin-2,
https://www.crunchbase.com/organization/seer-aerospace,
https://www.crunchbase.com/organization/landing-lion,
https://www.crunchbase.com/organization/kokko-inc,
https://www.crunchbase.com/organization/shopturn,
https://www.crunchbase.com/organization/local-crate-923f,
https://www.crunchbase.com/organization/bybe-inc,
https://www.crunchbase.com/organization/savitude-inc,
https://www.crunchbase.com/organization/teachertalent,
https://www.crunchbase.com/organization/directechlabs,
https://www.crunchbase.com/organization/air-tailor,
https://www.crunchbase.com/organization/storyxpress,
https://www.crunchbase.com/organization/spotcrowd,
https://www.crunchbase.com/organization/play-impossible,
https://www.crunchbase.com/organization/botnik-studios,
https://www.crunchbase.com/organization/ritmoji,
https://www.crunchbase.com/organization/novel-effect-inc,
https://www.crunchbase.com/organization/radiomaze,
https://www.crunchbase.com/organization/brook-ai,
https://www.crunchbase.com/organization/playfull,
https://www.crunchbase.com/organization/nameless,
https://www.crunchbase.com/organization/pulse-labs-b728,
https://www.crunchbase.com/organization/solutions-vending-international-inc,
https://www.crunchbase.com/organization/comet-ml,
https://www.crunchbase.com/organization/aspinity,
https://www.crunchbase.com/organization/slingshot-aerospace,
https://www.crunchbase.com/organization/comet-ml,
https://www.crunchbase.com/organization/hanzo,
https://www.crunchbase.com/organization/avisare,
https://www.crunchbase.com/organization/grit-virtual-inc,
https://www.crunchbase.com/organization/maslo,
https://www.crunchbase.com/organization/somatic-labs,
https://www.crunchbase.com/organization/nexusedge-inc,
https://www.crunchbase.com/organization/additive-rocket-corporation,
https://www.crunchbase.com/organization/casaiq,
https://www.crunchbase.com/organization/planetarians,
https://www.crunchbase.com/organization/stylindex,
https://www.crunchbase.com/organization/stackin,
https://www.crunchbase.com/organization/ampogee,
https://www.crunchbase.com/organization/vector-legal-method,
https://www.crunchbase.com/organization/upsie,
https://www.crunchbase.com/organization/blue-fever,
https://www.crunchbase.com/organization/heartbeat-3,
https://www.crunchbase.com/organization/impact-health,
https://www.crunchbase.com/organization/pulse-labs-b728,
https://www.crunchbase.com/organization/playfull,
https://www.crunchbase.com/organization/novel-effect-inc,
https://www.crunchbase.com/organization/vartega-carbon-fiber-recycling-llc,
https://www.crunchbase.com/organization/fathom-drone,
https://www.crunchbase.com/organization/wheeli,
https://www.crunchbase.com/organization/axle,
https://www.crunchbase.com/organization/seeva,
https://www.crunchbase.com/organization/freshcar,
https://www.crunchbase.com/organization/gridwise,
https://www.crunchbase.com/organization/derq,
https://www.crunchbase.com/organization/carma,
https://www.crunchbase.com/organization/botnik-studios,
https://www.crunchbase.com/organization/pulse-labs,
https://www.crunchbase.com/organization/air-tailor,
https://www.crunchbase.com/organization/turing-group-702e,
https://www.crunchbase.com/organization/getstream-io,
https://www.crunchbase.com/organization/care-academy,
https://www.crunchbase.com/organization/spotcrowd,
https://www.crunchbase.com/organization/aiva-health,
https://www.crunchbase.com/organization/tasso,
https://www.crunchbase.com/organization/choicemap,
https://www.crunchbase.com/organization/gyant,
https://www.crunchbase.com/organization/streamroot,
https://www.crunchbase.com/organization/2u-laundry,
https://www.crunchbase.com/organization/nrj,
https://www.crunchbase.com/organization/praktice-ai,
https://www.crunchbase.com/organization/terramanta,
https://www.crunchbase.com/organization/seremedi,
https://www.crunchbase.com/organization/paintheory,
https://www.crunchbase.com/organization/gtmhub,
https://www.crunchbase.com/organization/praktice-ai,
https://www.crunchbase.com/organization/wise-athena,
https://www.crunchbase.com/organization/aiva-health,
https://www.crunchbase.com/organization/tasso,
https://www.crunchbase.com/organization/narrativedx,
https://www.crunchbase.com/organization/yaypay-inc,
https://www.crunchbase.com/organization/sway-health,
https://www.crunchbase.com/organization/invio-2,
https://www.crunchbase.com/organization/storyxpress,
https://www.crunchbase.com/organization/cogni,
https://www.crunchbase.com/organization/magic-ai-corp,
https://www.crunchbase.com/organization/vlipsy,
https://www.crunchbase.com/organization/novo,
https://www.crunchbase.com/organization/7-chord,
https://www.crunchbase.com/organization/sigma-ratings,
https://www.crunchbase.com/organization/bild,
https://www.crunchbase.com/organization/qanta-ai,
https://www.crunchbase.com/organization/pathspark,
https://www.crunchbase.com/organization/realblocks,
https://www.crunchbase.com/organization/qanta-ai,
https://www.crunchbase.com/organization/7-chord,
https://www.crunchbase.com/organization/novo,
https://www.crunchbase.com/organization/bild,
https://www.crunchbase.com/organization/onemodel,
https://www.crunchbase.com/organization/pathspark,
https://www.crunchbase.com/organization/sigma-ratings,
https://www.crunchbase.com/organization/cardio-cube-ltd,
https://www.crunchbase.com/organization/ephemeral-solutions,
https://www.crunchbase.com/organization/slingshot-aerospace,
https://www.crunchbase.com/organization/solutions-vending-international-inc,
https://www.crunchbase.com/organization/seremedi,
https://www.crunchbase.com/organization/alpin,
https://www.crunchbase.com/organization/grafiti-app,
https://www.crunchbase.com/organization/rootine,
https://www.crunchbase.com/organization/omnix-labs,
https://www.crunchbase.com/organization/blind-tiger-communications,
https://www.crunchbase.com/organization/key-please,
https://www.crunchbase.com/organization/safeflights-inc,
https://www.crunchbase.com/organization/notch-technologies,
https://www.crunchbase.com/organization/aspinity,
https://www.crunchbase.com/organization/pioneer-square-labs,
https://www.crunchbase.com/organization/educative,
https://www.crunchbase.com/organization/flugauto,
https://www.crunchbase.com/organization/omnix-labs,
https://www.crunchbase.com/organization/ilivevr,
https://www.crunchbase.com/organization/novele,
https://www.crunchbase.com/organization/sophia-335f,
https://www.crunchbase.com/organization/fincura,
https://www.crunchbase.com/organization/kyso,
https://www.crunchbase.com/organization/ganaz,
https://www.crunchbase.com/organization/typingdna,
https://www.crunchbase.com/organization/rainway
https://www.crunchbase.com/organization/educative,
https://www.crunchbase.com/organization/downstream-5199,
https://www.crunchbase.com/organization/one-step,
https://www.crunchbase.com/organization/brio-systems,
https://www.crunchbase.com/organization/trustandwill,
`
let count = 0
function onlyUnique(value, index, self) {
	return self.indexOf(value) === index
}

let companies = rawInput.split(',\n').filter(onlyUnique)

for (let i = companies.length; i >= 0; i--) {
	if (companies[i] === '') {
		companies.pop()
	}
	if (usedInfo.includes(companies[i])) {
		let used = companies[i]
		console.log('REMOVED', companies.splice(used, 1))
		count++
	}
}
console.log('Amount of Companies Left: ' + companies.length)
module.exports = { companies }
